version: 6.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - echo Installing dependencies...
  pre build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started
      - grep -Fq "pratik" index.html
    finally:
      - echo This always runs even if the install command fails
  post build:
    commands:
      - echo Entered the post build phase...
      - echo Build completed
